# Numpy Tutorial.

## Importing numpy.

In [ ]:
import numpy as np

## Creating an ndarray from a list.

In [2]:
a = np.array([4, 3, 2, 1], dtype=np.int)

print(a)

[4 3 2 1]


## ndarray properties.

In [3]:
print(a)
print('a.ndim: ' + str(a.ndim))
print('a.shape: ' + str(a.shape))
print('a.dtype: ' + str(a.dtype))
print('a.size: ' + str(a.size))
print('type(a): ' + str(type(a)))

[4 3 2 1]
a.ndim: 1
a.shape: (4,)
a.dtype: int64
a.size: 4
type(a): <type 'numpy.ndarray'>


## Ascending numbers.

In [4]:
a = np.arange(50)
b = np.arange(20, 100, 10)

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[20 30 40 50 60 70 80 90]


## Reshape.

In [5]:
a = np.arange(50)
a = a.reshape(5, 10)
b = a.ravel()

print(a)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


## Numerical Operations.

In [6]:
b = np.arange(50) * 2
b = b.reshape(5, 10)

c = a + b

print(a)
print(b)
print(c)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]
[[  0   3   6   9  12  15  18  21  24  27]
 [ 30  33  36  39  42  45  48  51  54  57]
 [ 60  63  66  69  72  75  78  81  84  87]
 [ 90  93  96  99 102 105 108 111 114 117]
 [120 123 126 129 132 135 138 141 144 147]]


In [7]:
b = (np.arange(50, dtype=np.float) + 1) * 2
b = b.reshape(5, 10)

c = b / (a + 1)

print(a)
print(b)
print(c)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
 [ 22.  24.  26.  28.  30.  32.  34.  36.  38.  40.]
 [ 42.  44.  46.  48.  50.  52.  54.  56.  58.  60.]
 [ 62.  64.  66.  68.  70.  72.  74.  76.  78.  80.]
 [ 82.  84.  86.  88.  90.  92.  94.  96.  98. 100.]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]


## Indexing.

In [8]:
a = a.reshape(5, 10)

b = a[0:2, 0:2]
c = a[1:4, 2:8]

print(a)
print(b)
print(c)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 0  1]
 [10 11]]
[[12 13 14 15 16 17]
 [22 23 24 25 26 27]
 [32 33 34 35 36 37]]


## Array of Zeros or Ones.

In [9]:
ones = np.ones((2, 3, 3))
zeros = np.zeros((2, 3, 3))

print(ones)
print(zeros)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## Linear Spaces.

In [10]:
ls = np.linspace(0, 2, 10)

print(ls)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


## Random numbers.

In [11]:
integer = np.random.randint(0, 5)
uniform = np.random.random((5, 5))
normal = np.random.randn(5, 5)

print(integer)
print(uniform)
print(normal)

0
[[0.41246323 0.94569567 0.87404776 0.86502814 0.05061722]
 [0.15261007 0.98805929 0.62980522 0.31929855 0.17202783]
 [0.1730104  0.42378906 0.17902011 0.35045052 0.34939838]
 [0.51028546 0.38914264 0.6135708  0.92615643 0.25944768]
 [0.32633844 0.53638037 0.49167984 0.09101354 0.66974799]]
[[ 1.08170017  1.40346249  1.02224007  1.57406458  1.53526777]
 [ 1.30878227 -0.94867113  0.9557055   0.86745815  0.15653418]
 [-1.33412951  1.23105019  0.34150179  0.52266021  0.2151794 ]
 [-0.38056252  0.90868238 -0.94404165  0.83890578 -0.4655302 ]
 [-1.17986445 -0.10133269  0.93647779 -0.16543839 -1.20434072]]


## Comparisons.

In [12]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[0, 2, 0], [4, 0, 6]])

arr3 = arr1 == arr2
arr4 = arr1 != arr2
arr5 = arr1 > arr2
arr6 = arr1 < 2

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)

[[1 2 3]
 [4 5 6]]
[[0 2 0]
 [4 0 6]]
[[False  True False]
 [ True False  True]]
[[ True False  True]
 [False  True False]]
[[ True False  True]
 [False  True False]]
[[ True False False]
 [False False False]]


## Aggregate Functions.

In [15]:
a = np.arange(50, dtype=np.float).reshape(5, 10)

print(a)
print('sum ', a.sum())
print('min ', a.min())
print('max ', b.max(axis=0))
print('mean ', a.mean())
print('std ', np.std(a))
print('cumsum ', a.cumsum(axis=1))
print('median ', np.median(a))

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]]
('sum ', array([100., 105., 110., 115., 120., 125., 130., 135., 140., 145.]))
('min ', 0.0)
('max ', array([10, 11]))
('mean ', 24.5)
('std ', 14.430869689661812)
('cumsum ', array([[  0.,   1.,   3.,   6.,  10.,  15.,  21.,  28.,  36.,  45.],
       [ 10.,  21.,  33.,  46.,  60.,  75.,  91., 108., 126., 145.],
       [ 20.,  41.,  63.,  86., 110., 135., 161., 188., 216., 245.],
       [ 30.,  61.,  93., 126., 160., 195., 231., 268., 306., 345.],
       [ 40.,  81., 123., 166., 210., 255., 301., 348., 396., 445.]]))
('median ', 24.5)


## Sorting.

In [14]:
r = np.random.random((5, 5))

print(r)
print('sort ', np.sort(r))
print('sort ax 0 ', np.sort(r, axis=0))
print('sort ax 1 ', np.sort(r, axis=1))

[[0.09732698 0.55133675 0.5012974  0.91050703 0.98907492]
 [0.95519891 0.35757393 0.08590775 0.51858455 0.63340419]
 [0.65225658 0.61076057 0.49865861 0.89979847 0.13229754]
 [0.90878691 0.38042325 0.68432073 0.08546739 0.52465968]
 [0.39922783 0.99904774 0.41665023 0.83286636 0.68366694]]
('sort ', array([[0.09732698, 0.5012974 , 0.55133675, 0.91050703, 0.98907492],
       [0.08590775, 0.35757393, 0.51858455, 0.63340419, 0.95519891],
       [0.13229754, 0.49865861, 0.61076057, 0.65225658, 0.89979847],
       [0.08546739, 0.38042325, 0.52465968, 0.68432073, 0.90878691],
       [0.39922783, 0.41665023, 0.68366694, 0.83286636, 0.99904774]]))
('sort ax 0 ', array([[0.09732698, 0.35757393, 0.08590775, 0.08546739, 0.13229754],
       [0.39922783, 0.38042325, 0.41665023, 0.51858455, 0.52465968],
       [0.65225658, 0.55133675, 0.49865861, 0.83286636, 0.63340419],
       [0.90878691, 0.61076057, 0.5012974 , 0.89979847, 0.68366694],
       [0.95519891, 0.99904774, 0.68432073, 0.91050703, 0.989

## Boolean Indexing.

In [16]:
a = np.arange(50, dtype=np.float).reshape(5, 10)
print(a)

a[a > 20] = -1
print(a)

a[a == 15] = -1000
print(a)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]]
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]
[[    0.     1.     2.     3.     4.     5.     6.     7.     8.     9.]
 [   10.    11.    12.    13.    14. -1000.    16.    17.    18.    19.]
 [   20.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.]
 [   -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.]
 [   -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.]]
